### ISSUE TITLE
No communication with sensor

### ISSUE THREAD

**Issue by jnbht** [nzbullet/homebridge-homeqtt-alarm#4]
Sorry, i tried everything i could think of, but did not get the sensor to communicate with homebrdige/homekit.

So i installed homeqtt-alarm. It shows in Homekit and i can adjust Off/Away etc.

My Sensor is a Zigbee Doorsensor from Xiaomi. I get the status from the sensor in Node Red over Mqtt without any problems. There i have to input "zigbee2mqtt/SENSORNAME" to subscribe to the Sensor. The Output/Payload of it is:

{"topic":"zigbee2mqtt/SENSORNAME","payload":"{"battery":100, "voltage":3045, "contact":false, "linkquality":39}","qos":0,"retain":false,"_topic":"zigbee2mqtt/SENSORNAME","_msgid":"e4635fe1.3ccad"} 

My Config for Homeqtt is:

 "name": "Homeqtt",
            "accessory": "homebridge-homeqtt-alarm",
            "debug": true,
            "mqttConfig": {
                "url": "mqtt://localhost:1883"
            },
            "alarmTopics": {
                "messageTopic": "zigbee2mqtt/SENSORNAME",
                "setTargetStateTopic": "alarm/target",
                "getCurrentStateTopic": "alarm/current"
            },
            "alarmSettings": {
                "targetStates": {
                    "stayArm": true,
                    "awayArm": true,
                    "nightArm": true
                }
            },
            "sensor": [
                {
                    "sensorType": "contactSensor",
                    "location": "Front Door",
                    "MQTTCode": "zigbee2mqtt/SENSORNAME",
                    "enabled": true,
                    "allowStay": true,
                    "allowAway": true,
                    "allowNight": true
                }
            ],

What am i doing wrong?

**Comment by danieljbnz** [comment]
In `"MQTTCode": "zigbee2mqtt/SENSORNAME",` this should be a unique code to the sensor when it is 'opened'. Some sensor report open and closed, not sure if yours do but if they do make sure you are using the 'open' payload. I would probably suggest it should also just be `"MQTTCode": "SENSORNAME",` (omitting the zigbee2mqtt/). 

Note: I am assuming you have put SENSORNAME above for anonymity and this is usually a unique code.

Lastly I would also check your mqtt server address. "url": "mqtt://localhost:1883" and use the actual IP where your mqtt broker is running instead of localhost.

**Comment by jnbht** [comment]
Hi, thx for the ultrafast reply!

I am using my real IP. Just did not want to write it here. And the communication works for all my other Plugins (f.e. homebridge mqttthing) or with Node Red. So i think i do not insert the right variables for your plugin.

My Pi is running the Mosquito-Broker to manage the Mqtt-Communication. SENSORNAME is a friendlyname i can enter instead of using the very long unique number. It is changed on a core level and i don't know if i can use the numbers anymore. But as i said, i have no problem with this sensor and the nameing in my other plugins.

So to be sure, in "MQTTCode": i have to enter the Number/Name for the Mqtt-Broker right?

And if my Payload looks like this:
{"topic":"zigbee2mqtt/SENSORNAME","payload":"{"battery":100, "voltage":3045, "contact":false, "linkquality":39}","qos":0,"retain":false,"_topic":"zigbee2mqtt/SENSORNAME","_msgid":"e4635fe1.3ccad"}

What would you enter here:
"messageTopic": ?

Thanks for your help!

**Comment by danieljbnz** [comment]
When my RFBridge sends in a payload it looks like this: 
`{"Time":"2020-05-13T10:16:34","RfReceived":{"Sync":14050,"Low":480,"High":1370,"Data":"96930E","RfKey":"None"}}`
The code that is used is the **96930E**

This is sent to a topic where all messages are received when a sensor is triggered. So for me that is **tele/rfbridge/RESULT** This is so that no matter how many sensors you have they are all received by Homeqtt and it's the unique ID of each sensor that is what causes the trigger to happen. 

<img width="1163" alt="Screenshot 2020-05-13 at 091648" src="https://user-images.githubusercontent.com/24196566/81746565-d2f18580-94fa-11ea-919f-6c1f2ba034e6.png">

<img width="484" alt="Screenshot 2020-05-13 at 091939" src="https://user-images.githubusercontent.com/24196566/81746670-046a5100-94fb-11ea-864d-97aa7ad6f761.png">

**Comment by jnbht** [comment]
> When my RFBridge sends in a payload it looks like this:
> `{"Time":"2020-05-13T10:16:34","RfReceived":{"Sync":14050,"Low":480,"High":1370,"Data":"96930E","RfKey":"None"}}`
> The code that is used is the **96930E**
> 
I restarted and looked into the Logs. I don`t get any Errors. But Homeqtt still don't recognizes my Sensor. So i guess that the Payload has to look like yours or at least has to have the Data-Topic to work.

That makes it not usable for me, cause i am not using Sonoff. 
But thanks anyway. Otherwise it seems to be a great plugin ^^

**Comment by danieljbnz** [comment]
> So i guess that the Payload has to look like yours or at least has to have the Data-Topic to work.

Homeqtt just looks for a string inside the payload (the **MQTTcode** you have set) that is received to the **messageTopic** you set.

I have just changed my config so it looks like below and I am receiving the correct response from Homeqtt when I publish your payload to the topic (note the topic **is literally** zigbee2mqtt/SENSORNAME and the sensor name is SENSORNAME but I tried it with the zigbee2mqtt/SENSORNAME as well).

I did not that at the bottom of your example above it was missing the following afetr the last comment, not sure if you just didn't paste that: 
```
            "siren": {
                "enabled": false
            }
```

```
[5/13/2020, 12:29:37] [Homeqtt] Setup: Connected and subscribed to: zigbee2mqtt/SENSORNAME
[5/13/2020, 12:29:37] [Homeqtt] Setup: Connected and subscribed to: alarm/target
[5/13/2020, 12:29:37] [Homeqtt] Setup: Connected and subscribed to: alarm/current
[5/13/2020, 12:29:37] [Homeqtt] Setup: Enabled Alarm States - [ 'stayArm', 'awayArm', 'nightArm' ]
[5/13/2020, 12:29:37] [Homeqtt] Setup Complete
[5/13/2020, 12:29:37] [Homeqtt] Topic: alarm/current
[5/13/2020, 12:29:37] [Homeqtt] Alarm State: DISARMED
[5/13/2020, 12:29:37] [Homeqtt] Siren Status: DISARMED
[5/13/2020, 12:29:44] [Homeqtt] Setting state to: AWAY_ARM ( 1 )
[5/13/2020, 12:29:44] [Homeqtt] Topic: alarm/current
[5/13/2020, 12:29:44] [Homeqtt] Alarm State: AWAY_ARM
[5/13/2020, 12:29:44] [Homeqtt] Siren Status: AWAY_ARM
[5/13/2020, 12:29:52] [Homeqtt] Sensor Triggered: Front Door ( SENSORNAME )
[5/13/2020, 12:29:52] [Homeqtt] Topic: alarm/target
[5/13/2020, 12:29:52] [Homeqtt] Alarm State: ALARM_TRIGGERED
[5/13/2020, 12:29:52] [Homeqtt] Siren Status: ALARM_TRIGGERED
``` 
```
        {
            "name": "Homeqtt",
            "accessory": "homebridge-homeqtt-alarm",
            "debug": true,
            "mqttConfig": {
                "url": "mqtt://xxx.xxx.x.xx:1883"
            },
            "alarmTopics": {
                "messageTopic": "zigbee2mqtt/SENSORNAME",
                "setTargetStateTopic": "alarm/target",
                "getCurrentStateTopic": "alarm/current"
            },
            "alarmSettings": {
                "targetStates": {
                    "stayArm": true,
                    "awayArm": true,
                    "nightArm": true
                }
            },
            "sensor": [
                {
                    "sensorType": "contactSensor",
                    "location": "Front Door",
                    "MQTTCode": "SENSORNAME",
                    "enabled": true,
                    "allowStay": true,
                    "allowAway": true,
                    "allowNight": true
                }
            ],
            "siren": {
                "enabled": false
            }
        }
```

**Comment by danieljbnz** [comment]
I should note... even with debug on you only see entries in the logs **if** there is an alarm Triggered.

**Comment by danieljbnz** [comment]
Closed as no further comments
